name: Build

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_LEVEL: 31
      TARGET_HOST: aarch64-linux-android
    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27d
      - run: echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> "$GITHUB_ENV"
      - run: echo "CLANG_PATH=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/$TARGET_HOST$API_LEVEL-clang" >> "$GITHUB_ENV"
      - run: $CLANG_PATH -Wall -O3 -o chgdevinfo chgdevinfo.c
      - uses: actions/upload-artifact@v4
        with:
          name: Pixel-IMEI-Changer.zip
          path: |
            chgdevinfo
            module.prop
            post-fs-data.sh
